#!/usr/bin/env python

Import("env")

# import main_builders

env.main_sources = []

env_main = env.Clone()

env_main.add_source_files(env.main_sources, "*.cpp")

lib = env_main.add_library("main", env.main_sources)
env.Prepend(LIBS=[lib])
